import { cache } from 'react';
import { sql } from './connect';

/* This data is now coming from the database
const beers = [
  {
    id: 1,
    brand: 'Budweiser',
    type: 'American-style Lager',
    category: 'beer',
    origin: 'USA',
    price: 1.29,
  },
  {
    id: 2,
    brand: 'BudLight',
    type: 'American-style light Lager',
    category: 'beer',
    origin: 'USA',
    price: 1.29,
  },
  {
    id: 3,
    brand: 'Lagunitas',
    type: ' India Pale Ale',
    category: 'beer',
    origin: 'USA',
    price: 1.29,
  },
  {
    id: 4,
    brand: 'NewBelgium',
    type: 'Citrusy sweet Belgian-style beer',
    category: 'beer',
    origin: 'USA',
    price: 1.29,
  },
  {
    id: 5,
    brand: 'SierraNevada',
    type: 'Light-bodied, Pilsner-style Lager',
    category: 'beer',
    origin: 'USA',
    price: 1.29,
  },
  {
    id: 6,
    brand: 'Miller',
    type: 'American-style Lager',
    category: 'beer',
    origin: 'USA',
    price: 1.29,
  },
  {
    id: 7,
    brand: 'SamuelAdams',
    type: 'Boston Lager',
    category: 'beer',
    origin: 'USA',
    price: 1.29,
  },
  {
    id: 8,
    brand: 'Kona',
    type: 'Light Golden Ale',
    category: 'beer',
    origin: 'USA',
    price: 1.29,
  },
  {
    id: 9,
    brand: 'Breckenridge',
    type: 'German Amber Lager',
    category: 'beer',
    origin: 'USA',
    price: 1.29,
  },
  {
    id: 10,
    brand: 'Dreher',
    type: 'Lager',
    category: 'beer',
    origin: 'Hungary',
    price: 1.29,
  },
  {
    id: 11,
    brand: 'Soproni',
    type: 'Traditional Hungarian Lager',
    category: 'beer',
    origin: 'Hungary',
    price: 0.99,
  },
  {
    id: 12,
    brand: 'AranyAszok',
    type: 'Pilsner Lager',
    category: 'beer',
    origin: 'Hungary',
    price: 0.99,
  },
  {
    id: 13,
    brand: 'PecsiSor',
    type: 'Premium Lager',
    category: 'beer',
    origin: 'Hungary',
    price: 0.99,
  },
  {
    id: 14,
    brand: 'MonyoBrewing',
    type: ' Pale Lager',
    category: 'beer',
    origin: 'Hungary',
    price: 0.99,
  },
  {
    id: 15,
    brand: 'FeherNyul',
    type: 'IPA',
    category: 'beer',
    origin: 'Hungary',
    price: 0.99,
  },
  {
    id: 16,
    brand: 'Horizont',
    type: 'Pale Ale',
    category: 'beer',
    origin: 'Hungary',
    price: 0.99,
  },
  {
    id: 17,
    brand: 'Rizmajer',
    type: 'Pale Lager',
    category: 'beer',
    origin: 'Hungary',
    price: 0.99,
  },
  {
    id: 18,
    brand: 'Hubris',
    type: 'very light Pale Ale',
    category: 'beer',
    origin: 'Hungary',
    price: 0.99,
  },
  {
    id: 19,
    brand: 'Foti',
    type: 'unpasteurized Zwickelbier',
    category: 'beer',
    origin: 'Hungary',
    price: 0.99,
  },
  {
    id: 20,
    brand: 'Ottakringer',
    type: 'Vienna Lager',
    category: 'beer',
    origin: 'Austria',
    price: 1.16,
  },
  {
    id: 21,
    brand: 'Gosser',
    type: 'Austrian Märzen',
    category: 'beer',
    origin: 'Austria',
    price: 1.16,
  },
  {
    id: 22,
    brand: 'Stiegl',
    type: 'thirst-quenching Lager',
    category: 'beer',
    origin: 'Austria',
    price: 1.16,
  },
  {
    id: 23,
    brand: 'Zipfer',
    type: 'Pale Bock',
    category: 'beer',
    origin: 'Austria',
    price: 1.16,
  },
  {
    id: 24,
    brand: 'Edelweiss',
    type: 'Wheat Beer',
    category: 'beer',
    origin: 'Austria',
    price: 1.16,
  },
  {
    id: 25,
    brand: 'Egger',
    type: 'easy-drinking malty Lager',
    category: 'beer',
    origin: 'Austria',
    price: 1.16,
  },
  {
    id: 26,
    brand: 'Wieselburger',
    type: 'an easy, simple, tasteless Lager',
    category: 'beer',
    origin: 'Austria',
    price: 1.16,
  },
  {
    id: 27,
    brand: 'Puntigamer',
    type: 'European Pale Lager style',
    category: 'beer',
    origin: 'Austria',
    price: 1.16,
  },
  {
    id: 28,
    brand: 'Zillertal',
    type: 'Märzen',
    category: 'beer',
    origin: 'Austria',
    price: 1.16,
  },
  {
    id: 29,
    brand: 'Solsch',
    type: 'Lager',
    category: 'beer',
    origin: 'Austria',
    price: 1.16,
  },
  {
    id: 30,
    brand: 'Paulaner',
    type: 'Amber Lager ',
    category: 'beer',
    origin: 'Germany',
    price: 1.59,
  },
  {
    id: 31,
    brand: 'Wernesgruner',
    type: 'German Pilsner',
    category: 'beer',
    origin: 'Germany',
    price: 1.59,
  },
  {
    id: 32,
    brand: 'Erdinger',
    type: 'Light Wheat Ale',
    category: 'beer',
    origin: 'Germany',
    price: 1.59,
  },
  {
    id: 33,
    brand: 'Becks',
    type: 'characterful Pilsner',
    category: 'beer',
    origin: 'Germany',
    price: 1.59,
  },
  {
    id: 34,
    brand: 'Lowenbrau',
    type: 'Helles Lager',
    category: 'beer',
    origin: 'Germany',
    price: 1.59,
  },
  {
    id: 35,
    brand: 'Holsten',
    type: 'German Pilsner',
    category: 'beer',
    origin: 'Germany',
    price: 1.59,
  },
  {
    id: 36,
    brand: 'Hofbrau',
    type: 'Pale Lager',
    category: 'beer',
    origin: 'Germany',
    price: 1.59,
  },
  {
    id: 37,
    brand: 'Karlsberg',
    type: 'Natur Radler',
    category: 'beer',
    origin: 'Germany',
    price: 1.59,
  },
  {
    id: 38,
    brand: 'Tegernseer',
    type: 'Helles Lager',
    category: 'beer',
    origin: 'Germany',
    price: 1.59,
  },
  {
    id: 39,
    brand: 'Kozel',
    type: 'Pale Lager',
    category: 'beer',
    origin: 'Czech Republic',
    price: 1.37,
  },
  {
    id: 40,
    brand: 'PilsnerUrquell',
    type: 'Pale Lager',
    category: 'beer',
    origin: 'Czech Republic',
    price: 1.37,
  },
  {
    id: 41,
    brand: 'Staropramen',
    type: 'Premium Lager',
    category: 'beer',
    origin: 'Czech Republic',
    price: 1.37,
  },
  {
    id: 42,
    brand: 'Branik',
    type: 'Czech Pale Lager',
    category: 'beer',
    origin: 'Czech Republic',
    price: 1.37,
  },
  {
    id: 43,
    brand: 'Bernard',
    type: 'Champagne type beer',
    category: 'beer',
    origin: 'Czech Republic',
    price: 1.37,
  },
  {
    id: 44,
    brand: 'Krusovice',
    type: 'Pale',
    category: 'beer',
    origin: 'Czech Republic',
    price: 1.37,
  },
  {
    id: 45,
    brand: 'Gambrinus',
    type: 'Czech Pale',
    category: 'beer',
    origin: 'Czech Republic',
    price: 1.37,
  },
  {
    id: 46,
    brand: 'Lobkowicz',
    type: 'Czech Pilsner',
    category: 'beer',
    origin: 'Czech Republic',
    price: 1.37,
  },
  {
    id: 47,
    brand: 'CernaHora',
    type: 'Fruit Beer',
    category: 'beer',
    origin: 'Czech Republic',
    price: 1.37,
  },
  {
    id: 48,
    brand: 'Starobrno',
    type: 'Czech light Lager',
    category: 'beer',
    origin: 'Czech Republic',
    price: 1.37,
  },
  {
    id: 49,
    brand: 'Sol',
    type: 'Mexican Lager',
    category: 'beer',
    origin: 'Mexico',
    price: 1.29,
  },
  {
    id: 50,
    brand: 'Corona',
    type: 'Alcohol-free Mexican Lager',
    category: 'beer',
    origin: 'Mexico',
    price: 1.29,
  },
  {
    id: 51,
    brand: 'NegraModelo',
    type: 'Munich Dunkel-style Lager',
    category: 'beer',
    origin: 'Mexico',
    price: 1.29,
  },
  {
    id: 52,
    brand: 'Victoria',
    type: 'Vienna-style Lager',
    category: 'beer',
    origin: 'Mexico',
    price: 1.29,
  },
  {
    id: 53,
    brand: 'Pacifico',
    type: 'Pilsner-style Lager',
    category: 'beer',
    origin: 'Mexico',
    price: 1.29,
  },
  {
    id: 54,
    brand: 'Saigon',
    type: 'Vietnam Pilsner-type Lager',
    category: 'beer',
    origin: 'Asia',
    price: 0.89,
  },
  {
    id: 55,
    brand: 'BeerLao',
    type: 'Laos Pilsner',
    category: 'beer',
    origin: 'Asia',
    price: 0.89,
  },
  {
    id: 56,
    brand: 'ChangBeer',
    type: 'European Style Lager Beer',
    category: 'beer',
    origin: 'Asia',
    price: 0.89,
  },
  {
    id: 57,
    brand: 'Leo',
    type: 'Full-flavored standard Lager',
    category: 'beer',
    origin: 'Asia',
    price: 0.89,
  },
  {
    id: 58,
    brand: 'SanMiguel',
    type: 'Pilsner-style Lager',
    category: 'beer',
    origin: 'Asia',
    price: 0.89,
  },
  {
    id: 59,
    brand: 'Leffe',
    type: 'Belgian Blonde Ale style',
    category: 'beer',
    origin: 'Belgium',
    price: 1.09,
  },
  {
    id: 60,
    brand: 'Duvel',
    type: 'Strong Golden Pale Ale',
    category: 'beer',
    origin: 'Belgium',
    price: 1.09,
  },
  {
    id: 61,
    brand: 'Kasteel',
    type: 'Belgian Red Strong Fruit Ale',
    category: 'beer',
    origin: 'Belgium',
    price: 1.09,
  },
  {
    id: 62,
    brand: 'SaisonDupont',
    type: 'classic Belgian seasonal Ale',
    category: 'beer',
    origin: 'Belgium',
    price: 1.09,
  },
  {
    id: 63,
    brand: 'StFeuillien',
    type: 'Traditional Farmhouse Ale',
    category: 'beer',
    origin: 'Belgium',
    price: 1.09,
  },
]; */

type Beer = {
  id: number;
  brand: string;
  type: string;
  category: string;
  origin: string;
  price: number;
};

export const getBeersInsecure = cache(async () => {
  const beers = await sql<Beer[]>`
      SELECT * FROM beers
      `;

  return beers;
});

export const getBeerInsecure = cache(async (id: number) => {
  const [beers] = await sql<Beer[]>`
      SELECT * FROM beers WHERE id = ${id}
      `;

  return beers;
});
